apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: temp-predictor-api
  newName: ghcr.io/konradmarcinpsiuk/bda_ca_mlops/temp-predictor-api
  newTag: c863dad
