apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

images:
  - name: temp-predictor-api
    newName: ghcr.io/REPLACE_ME/temp-predictor-api
    newTag: latest
